# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ca3ace74952172ed4150e99c1f95c7f8162f4509ae6576f4e262df5453c494e4e813d5468029ebee809142e4d82f660e52eaa4c5567d0cab50337006c7e5b02b

test:
  secret_key_base: 6b027764273237019d60e39ab59c7d40039d09fe23a0703c045f40b2d57207da44143ae67db12af92e270bc203706187ff8a955f8a42c993d56301613111b945

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
